/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import core.entities.*;
import core.helpers.tools.EnumsBuilder;
import java.sql.Date;

import java.time.Instant;
import java.time.LocalDate;

/**
 * @author pacome
 */
public class CreerContact extends javax.swing.JFrame {

    /**
     * Creates new form CreerContact
     */
    private final MainFrameApplication mainFrameApplication;

    public CreerContact(MainFrameApplication mainFrameApplication) {
        this.mainFrameApplication = mainFrameApplication;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        sidenav1 = new javax.swing.JPanel();
        label6 = new java.awt.Label();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        label17 = new java.awt.Label();
        label18 = new java.awt.Label();
        dateNaissance = new javax.swing.JTextField();
        adresse = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        niveau = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        type = new javax.swing.JComboBox<>();
        cycle = new javax.swing.JComboBox<>();
        label19 = new java.awt.Label();
        label20 = new java.awt.Label();
        telephone = new javax.swing.JTextField();
        statutEnseignant = new javax.swing.JComboBox<>();
        label21 = new java.awt.Label();
        salaire = new javax.swing.JTextField();
        label24 = new java.awt.Label();
        categorie = new javax.swing.JTextField();
        label23 = new java.awt.Label();
        label22 = new java.awt.Label();
        indiceSalaire = new javax.swing.JTextField();
        label25 = new java.awt.Label();
        statutAgent = new javax.swing.JComboBox<>();
        annuler = new javax.swing.JButton();
        creer = new javax.swing.JButton();
        occupation = new javax.swing.JTextField();
        label26 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidenav1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        label6.setFont(new java.awt.Font("Laksaman", 1, 18)); // NOI18N
        label6.setText("Date naiss.");

        label12.setFont(new java.awt.Font("Laksaman", 1, 18)); // NOI18N
        label12.setText("Adresse");

        label13.setFont(new java.awt.Font("Laksaman", 1, 18)); // NOI18N
        label13.setText("Entrez les informations du nouveau Contact ");

        label15.setFont(new java.awt.Font("Laksaman", 1, 18)); // NOI18N
        label15.setText("Type de contact");

        label16.setFont(new java.awt.Font("Laksaman", 1, 18)); // NOI18N
        label16.setText("Nom");

        label17.setFont(new java.awt.Font("Laksaman", 1, 18)); // NOI18N
        label17.setText("Email");

        label18.setFont(new java.awt.Font("Laksaman", 1, 18)); // NOI18N
        label18.setText("Téléphone");

        dateNaissance.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        dateNaissance.setMinimumSize(new java.awt.Dimension(45, 35));
        dateNaissance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateNaissanceActionPerformed(evt);
            }
        });

        adresse.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        adresse.setMinimumSize(new java.awt.Dimension(45, 35));
        adresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adresseActionPerformed(evt);
            }
        });

        nom.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        nom.setMinimumSize(new java.awt.Dimension(45, 35));
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });

        niveau.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        niveau.setMinimumSize(new java.awt.Dimension(45, 35));
        niveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                niveauActionPerformed(evt);
            }
        });

        email.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        email.setMinimumSize(new java.awt.Dimension(45, 35));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Etudiant", "Enseignant", "Agent" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        type.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                typePropertyChange(evt);
            }
        });

        cycle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LICENCE", "INGENIEUR" }));

        label19.setFont(new java.awt.Font("Laksaman", 1, 18)); // NOI18N
        label19.setText("Niveau");

        label20.setFont(new java.awt.Font("Laksaman", 1, 18)); // NOI18N
        label20.setText("Cycle");

        telephone.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        telephone.setMinimumSize(new java.awt.Dimension(45, 35));
        telephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephoneActionPerformed(evt);
            }
        });

        statutEnseignant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VACATAIRE", "PERMANENT" }));

        label21.setFont(new java.awt.Font("Laksaman", 1, 18)); // NOI18N
        label21.setText("Statut");

        salaire.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        salaire.setMinimumSize(new java.awt.Dimension(45, 35));
        salaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaireActionPerformed(evt);
            }
        });

        label24.setFont(new java.awt.Font("Laksaman", 1, 18)); // NOI18N
        label24.setText("Salaire");

        categorie.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        categorie.setMinimumSize(new java.awt.Dimension(45, 35));
        categorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorieActionPerformed(evt);
            }
        });

        label23.setFont(new java.awt.Font("Laksaman", 1, 18)); // NOI18N
        label23.setText("Categorie");

        label22.setFont(new java.awt.Font("Laksaman", 1, 18)); // NOI18N
        label22.setText("Indice de Salaire");

        indiceSalaire.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        indiceSalaire.setMinimumSize(new java.awt.Dimension(45, 35));
        indiceSalaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indiceSalaireActionPerformed(evt);
            }
        });

        label25.setFont(new java.awt.Font("Laksaman", 1, 18)); // NOI18N
        label25.setText("Statut");

        statutAgent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TEMPORAIRE", "STAGIAIRE", "PERMANENT" }));

        annuler.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        creer.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        creer.setText("Enregistrer");
        creer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerActionPerformed(evt);
            }
        });

        occupation.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        occupation.setMinimumSize(new java.awt.Dimension(45, 35));
        occupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occupationActionPerformed(evt);
            }
        });

        label26.setFont(new java.awt.Font("Laksaman", 1, 18)); // NOI18N
        label26.setText("Ocupation");

        javax.swing.GroupLayout sidenav1Layout = new javax.swing.GroupLayout(sidenav1);
        sidenav1.setLayout(sidenav1Layout);
        sidenav1Layout.setHorizontalGroup(
            sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidenav1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidenav1Layout.createSequentialGroup()
                        .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(sidenav1Layout.createSequentialGroup()
                        .addGroup(sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sidenav1Layout.createSequentialGroup()
                                .addGroup(sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(label18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(label12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(label16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(salaire, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(categorie, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(sidenav1Layout.createSequentialGroup()
                                .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(statutAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(indiceSalaire, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sidenav1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(sidenav1Layout.createSequentialGroup()
                                        .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                        .addComponent(niveau, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(sidenav1Layout.createSequentialGroup()
                                        .addGroup(sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(sidenav1Layout.createSequentialGroup()
                                                .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidenav1Layout.createSequentialGroup()
                                                .addGroup(sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(label26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(label6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(label17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cycle, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(occupation, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(sidenav1Layout.createSequentialGroup()
                                        .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(statutEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(176, 176, 176))
                                    .addGroup(sidenav1Layout.createSequentialGroup()
                                        .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidenav1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(193, 193, 193))))))
            .addGroup(sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidenav1Layout.createSequentialGroup()
                    .addContainerGap(825, Short.MAX_VALUE)
                    .addComponent(creer, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );
        sidenav1Layout.setVerticalGroup(
            sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidenav1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sidenav1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(label16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addComponent(nom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(sidenav1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(dateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(label17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sidenav1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telephone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label26, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(occupation, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidenav1Layout.createSequentialGroup()
                        .addGroup(sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cycle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sidenav1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(niveau, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidenav1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(sidenav1Layout.createSequentialGroup()
                        .addGroup(sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salaire, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categorie, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidenav1Layout.createSequentialGroup()
                        .addComponent(statutEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(sidenav1Layout.createSequentialGroup()
                        .addGroup(sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(indiceSalaire, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statutAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 54, Short.MAX_VALUE))))
            .addGroup(sidenav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidenav1Layout.createSequentialGroup()
                    .addContainerGap(492, Short.MAX_VALUE)
                    .addComponent(creer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sidenav1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sidenav1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateNaissanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateNaissanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateNaissanceActionPerformed

    private void adresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adresseActionPerformed

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void niveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_niveauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_niveauActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void telephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneActionPerformed

    private void salaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaireActionPerformed

    private void categorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categorieActionPerformed

    private void indiceSalaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indiceSalaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_indiceSalaireActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        // TODO add your handling code here:
        this.dispose();
        mainFrameApplication.setVisible(true);
    }//GEN-LAST:event_annulerActionPerformed

    private void creerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerActionPerformed
        // TODO add your handling code here:

        Repertoire repertoire = mainFrameApplication.getRepertoire();
        // creer le contact

        Contact contact;

        String user = (String) type.getSelectedItem();
        try {
            if (user == "Etudiant") {
                contact = new Etudiant(
                        EnumsBuilder.cycleEnumFromString((String) cycle.getSelectedItem()),
                        "etu" + Integer.toString((int) (Math.random() * 500000) % 500000), nom.getText(),  Date.valueOf(LocalDate.of(2004, 06, 29)), adresse.getText(), email.getText(), telephone.getText(), niveau.getText());

            } else if (user == "Enseignant") {
                contact = new Enseignant(
                        EnumsBuilder.statutEnseignantEnumFromString((String) statutEnseignant.getSelectedItem()),
                        "ens" + Integer.toString((int) (Math.random() * 500000) % 500000), nom.getText(),  Date.valueOf(LocalDate.of(2004, 06, 29)), adresse.getText(), email.getText(), telephone.getText());
            } else {
                contact = new Agent(
                        Float.parseFloat(salaire.getText()),
                        EnumsBuilder.statutAgentEnumFromString((String) statutEnseignant.getSelectedItem()), categorie.getText(), indiceSalaire.getText(), occupation.getText(),
                        "agent" + Integer.toString((int) (Math.random() * 500000) % 500000), nom.getText(), Date.valueOf(LocalDate.of(2004, 06, 29)), adresse.getText(), email.getText(), telephone.getText());
            }

        } catch (Exception e) {
            MainFrameApplication.showErrorStatic("Erreur de base de donnée", "Une erreur est survenue lors de l'enregistremement");
            e.printStackTrace();
            return;
        }

        repertoire.ajouterContact(contact);
        
        System.out.println(repertoire.getContacts().size());

        mainFrameApplication.loadTableContent(repertoire.getContacts());
        mainFrameApplication.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_creerActionPerformed

    private void occupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occupationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_occupationActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void typePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_typePropertyChange
        // TODO add your handling code here:
        
        System.out.println("Prop changed");
    }//GEN-LAST:event_typePropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresse;
    private javax.swing.JButton annuler;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField categorie;
    private javax.swing.JButton creer;
    private javax.swing.JComboBox<String> cycle;
    private javax.swing.JTextField dateNaissance;
    private javax.swing.JTextField email;
    private javax.swing.JTextField indiceSalaire;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private java.awt.Label label20;
    private java.awt.Label label21;
    private java.awt.Label label22;
    private java.awt.Label label23;
    private java.awt.Label label24;
    private java.awt.Label label25;
    private java.awt.Label label26;
    private java.awt.Label label6;
    private javax.swing.JTextField niveau;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField occupation;
    private javax.swing.JTextField salaire;
    private javax.swing.JPanel sidenav1;
    private javax.swing.JComboBox<String> statutAgent;
    private javax.swing.JComboBox<String> statutEnseignant;
    private javax.swing.JTextField telephone;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
