/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.sql.*;
import javax.swing.UIManager;
import com.formdev.flatlaf.FlatDarkLaf;
import core.Agent;

import core.Contact;
import core.Enseignant;
import core.Etudiant;
import core.Repertoire;
import javax.swing.UnsupportedLookAndFeelException;
import ui.creation.MainCreation;
import ui.liste.ListeContacts;

/**
 *
 * @author pc
 */
public class MainFrmApplication extends javax.swing.JFrame {

    /**
     * Creates new form MainFrmApplication2
     */
    public MainFrmApplication() {
        // setting default theme
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (UnsupportedLookAndFeelException e) {
        }        
        
        // initialisation du repertoire
        this.repertoire = new Repertoire();
        initComponents();
        setLocationRelativeTo(null);
        
        Etudiant etudiant = new Etudiant("21P246", "Mogou Igor Green", new java.util.Date(), "1234melen", "igormogou86@gmail.com", "690909090", "3GI", Etudiant.Cycle.Ingenieur);
        Etudiant etudiant2 = new Etudiant("21P330", "Moga Igora Greenelle", new java.util.Date(), "1345yde", "igoramoga86@gmail.com", "696969696", "3GI", Etudiant.Cycle.Licence);
        Enseignant enseignant = new Enseignant("AF3UY1", "Pr. GG",  new java.util.Date(), "1456doula", "GG@GG.com", "6GGGGGGGG", Enseignant.Statut.Permanent);
        Enseignant enseignant2 = new Enseignant("AF2UY1", "Pr. GGA",  new java.util.Date(), "1478medssa", "GGA@GGA.com", "6GGAGGAGGAGGA", Enseignant.Statut.Vacataire);
        Agent agent = new Agent("AF3AFK2021", "Agent GG", new java.util.Date(), "agent@agent.com", "456nkoabang", "697949794", 600000, Agent.Statut.Stagiaire, "CategorieA", 10, "Manager");
        
        this.repertoire.ajouterContact(etudiant);        
        this.repertoire.ajouterContact(etudiant2);
        this.repertoire.ajouterContact(enseignant);
        this.repertoire.ajouterContact(enseignant2);
        this.repertoire.ajouterContact(agent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Eras Bd BT", 0, 18)); // NOI18N
        jLabel1.setText("CONTACTS MANAGER");

        jButton6.setText("Afficher contacts");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setText("Créer contact");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jMenu1.setText("Fichier");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Enregister");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Quitter");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.enregistrer();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        java.awt.EventQueue.invokeLater(() -> 
        { 
            this.mainCreationWindow = new MainCreation(this.repertoire);
            this.mainCreationWindow.setVisible(true);
        });   
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        java.awt.EventQueue.invokeLater(() -> 
        { 
            this.listeContacts = new ListeContacts(this.repertoire, this.connection);
            this.listeContacts.setVisible(true);
        });   
    }//GEN-LAST:event_jButton6ActionPerformed

    private void enregistrer() {
        for (Contact contact : repertoire.getRepertoire()){
            contact.insererContact(this.connection);
        }
    }

    public void main() {
        // start by setting up connection to database
        final String JDBC_URL = "jdbc:mysql://localhost:3306/";
        final String USER = "root";
        final String PASSWORD = "#Green0ps360Admin";
        final String DATABASE_NAME = "REPERTOIRE";
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            connection = DriverManager.getConnection(JDBC_URL + DATABASE_NAME,USER, PASSWORD);
        } catch (ClassNotFoundException | SQLException e) {
            System.exit(-1);
        }
    }
    
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> 
        { 
            MainFrmApplication app = new MainFrmApplication();
            app.main();
            app.setVisible(true); 
        });   
    }
    
    // liste contact frame
    ListeContacts listeContacts;
    
    // contact creation frame
    MainCreation mainCreationWindow;
    
    // java sql connectivity
    private Connection connection = null;
    private Repertoire repertoire = null;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
